name: CI

on:
  push:
    branches: ["**"]
    tags: ["v*"]
  pull_request:

jobs:
  ci:
    uses: https://harton.dev/james/workflows/.forgejo/workflows/nerves-app.yml@main
    runs-on: docker
    with:
      targets: "rpi0_2"
      assets_deploy_enabled: true
    secrets: inherit
