defmodule PiFi.Repo.Migrations.AddItemAddedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:playback_items) do
      add :added_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:playback_items) do
      remove :added_at
    end
  end
end