defmodule PiFi.Repo.Migrations.AirplayPairings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:airplay_pairings, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :name, :text
      add :public_key, :binary, null: false
      add :identifier, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:airplay_pairings, [:identifier],
             name: "airplay_pairings_identifier_index"
           )
  end

  def down do
    drop_if_exists unique_index(:airplay_pairings, [:identifier],
                     name: "airplay_pairings_identifier_index"
                   )

    drop table(:airplay_pairings)
  end
end