defmodule MyHiFi.Repo.Migrations.AddStationsAndSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stations, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :click_count, :bigint, null: false
      add :last_played_at, :utc_datetime_usec
      add :favourite, :boolean, null: false
      add :artwork_url, :text
      add :tags, {:array, :text}, null: false, default: []
      add :language, :text
      add :country_code, :text
      add :hls, :boolean, null: false
      add :bitrate, :bigint
      add :codec, :text
      add :stream_url, :text, null: false
      add :title, :text, null: false
      add :remote_id, :text
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:stations, [:remote_id], name: "stations_remote_id_index")

    create table(:settings, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :value, :text, null: false
      add :key, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:settings, [:key], name: "settings_key_index")
  end

  def down do
    drop_if_exists unique_index(:settings, [:key], name: "settings_key_index")

    drop table(:settings)

    drop_if_exists unique_index(:stations, [:remote_id], name: "stations_remote_id_index")

    drop table(:stations)
  end
end