defmodule PiFi.Repo.Migrations.ShuffleTheQueue do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:playback_queue) do
      add :shuffle_position, :bigint
    end
  end

  def down do
    alter table(:playback_queue) do
      remove :shuffle_position
    end
  end
end