defmodule MyHiFi.Repo.Migrations.AddPlaylists do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:playback_playlists, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :name, :citext, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:playback_playlists, [:name], name: "playback_playlists_name_index")

    create table(:playback_playlist_entries, primary_key: false) do
      add :item_id,
          references(:playback_items,
            column: :id,
            name: "playback_playlist_entries_item_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false

      add :playlist_id,
          references(:playback_playlists,
            column: :id,
            name: "playback_playlist_entries_playlist_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :position, :bigint, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:playback_playlist_entries, ["playlist_id"])
  end

  def down do
    drop_if_exists index(:playback_playlist_entries, ["playlist_id"],
                     name: "playback_playlist_entries_playlist_id_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `playback_playlist_entries` table without the `playback_playlist_entries_playlist_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `playback_playlist_entries` table without the `playback_playlist_entries_item_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:playback_playlist_entries)

    drop_if_exists unique_index(:playback_playlists, [:name],
                     name: "playback_playlists_name_index"
                   )

    drop table(:playback_playlists)
  end
end