defmodule PiFi.Repo.Migrations.PersistThePlayQueue do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:playback_queue, primary_key: false) do
      add :item_id,
          references(:playback_items,
            column: :id,
            name: "playback_queue_item_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false

      add :playing, :boolean, null: false
      add :position, :bigint, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `playback_queue` table without the `playback_queue_item_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:playback_queue)
  end
end