defmodule MyHiFi.Repo.Migrations.AddPlexSource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:playback_items) do
      add :source_key, :text
    end
  end

  def down do
    alter table(:playback_items) do
      remove :source_key
    end
  end
end