defmodule PiFi.Repo.Migrations.PlexPlaylistsMirror do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  # **The default is not decoration, and the generator left it out.** SQLite refuses to
  # add a `NOT NULL` column to a table that holds rows unless one is given, and every
  # playlist on a device today is one that a person made. See
  # `PiFi.Playback.Playlist.device_source/0`.
  def up do
    alter table(:playback_playlists) do
      add :source, :text, null: false, default: "device"
      add :source_ref, :text
      add :source_updated_at, :utc_datetime_usec
      add :last_seen_at, :utc_datetime_usec
    end

    drop_if_exists unique_index(:playback_playlists, [:name],
                     name: "playback_playlists_name_index"
                   )

    create unique_index(:playback_playlists, [:source, :name],
             name: "playback_playlists_name_index"
           )

    create unique_index(:playback_playlists, [:source, :source_ref],
             name: "playback_playlists_source_playlist_index"
           )
  end

  def down do
    drop_if_exists unique_index(:playback_playlists, [:source, :source_ref],
                     name: "playback_playlists_source_playlist_index"
                   )

    drop_if_exists unique_index(:playback_playlists, [:source, :name],
                     name: "playback_playlists_name_index"
                   )

    create unique_index(:playback_playlists, [:name], name: "playback_playlists_name_index")

    alter table(:playback_playlists) do
      remove :last_seen_at
      remove :source_updated_at
      remove :source_ref
      remove :source
    end
  end
end