defmodule MyHiFi.Repo.Migrations.AddItemBrowseIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:playback_items, ["source", "kind", "title"])
  end

  def down do
    drop_if_exists index(:playback_items, ["source", "kind", "title"],
                     name: "playback_items_source_kind_title_index"
                   )
  end
end