defmodule MyHiFi.Repo.Migrations.AddCacheEntryWeight do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cache_entries) do
      add :weight, :bigint, null: false
    end
  end

  def down do
    alter table(:cache_entries) do
      remove :weight
    end
  end
end