defmodule MyHiFi.Repo.Migrations.AddTheHistoryOfWhatAPersonHeard do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:playback_items) do
      add :last_started_at, :utc_datetime_usec
    end

    execute("""
    CREATE INDEX playback_items_last_started_at_index
    ON playback_items (last_started_at)
    WHERE last_started_at IS NOT NULL
    """)
  end

  def down do
    execute("""
    DROP INDEX playback_items_last_started_at_index
    """)

    alter table(:playback_items) do
      remove :last_started_at
    end
  end
end