defmodule PiFi.Repo.Migrations.AddPodcastShowsAndEpisodes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:podcast_shows, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_error, :text
      add :last_fetched_at, :utc_datetime_usec
      add :subscribed, :boolean, null: false
      add :artwork_url, :text
      add :description, :text
      add :author, :text
      add :title, :text, null: false
      add :index_id, :bigint
      add :feed_url, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:podcast_shows, [:feed_url], name: "podcast_shows_feed_url_index")

    create table(:podcast_episodes, primary_key: false) do
      add :show_id,
          references(:podcast_shows,
            column: :id,
            name: "podcast_episodes_show_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :played, :boolean, null: false
      add :position_ms, :bigint, null: false
      add :artwork_url, :text
      add :published_at, :utc_datetime_usec
      add :duration_ms, :bigint
      add :byte_length, :bigint
      add :mime_type, :text
      add :audio_url, :text, null: false
      add :description, :text
      add :subtitle, :text
      add :title, :text
      add :guid, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:podcast_episodes, [:show_id, :guid],
             name: "podcast_episodes_guid_of_show_index"
           )
  end

  def down do
    drop_if_exists unique_index(:podcast_episodes, [:show_id, :guid],
                     name: "podcast_episodes_guid_of_show_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `podcast_episodes` table without the `podcast_episodes_show_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:podcast_episodes)

    drop_if_exists unique_index(:podcast_shows, [:feed_url], name: "podcast_shows_feed_url_index")

    drop table(:podcast_shows)
  end
end