defmodule MyHiFi.Repo.Migrations.AddCounts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:playback_items, ["parent_id"])

    create index(:playback_item_facets, ["facet_id"])
  end

  def down do
    drop_if_exists index(:playback_item_facets, ["facet_id"],
                     name: "playback_item_facets_facet_id_index"
                   )

    drop_if_exists index(:playback_items, ["parent_id"], name: "playback_items_parent_id_index")
  end
end