defmodule MyHiFi.Repo.Migrations.IndexTheExpressionsThatAshWrites do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    DROP INDEX playback_items_source_kind_title_nocase_index
    """)

    execute("""
    CREATE INDEX playback_items_source_kind_added_at_index
    ON playback_items (source, CAST(kind AS TEXT), added_at)
    """)

    execute("""
    CREATE INDEX playback_items_source_favourite_title_nocase_index
    ON playback_items (source, CAST(favourite AS INTEGER), title COLLATE NOCASE)
    """)

    execute("""
    CREATE INDEX playback_items_source_kind_title_nocase_index
    ON playback_items (source, CAST(kind AS TEXT), title COLLATE NOCASE)
    """)
  end

  def down do
    execute("""
    DROP INDEX playback_items_source_kind_title_nocase_index
    """)

    execute("""
    DROP INDEX playback_items_source_favourite_title_nocase_index
    """)

    execute("""
    DROP INDEX playback_items_source_kind_added_at_index
    """)

    execute("""
    CREATE INDEX playback_items_source_kind_title_nocase_index
    ON playback_items (source, kind, title COLLATE NOCASE)
    """)
  end
end