defmodule PiFi.Repo.Migrations.AddPlaybackCatalogue do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:playback_items, primary_key: false) do
      add :parent_id,
          references(:playback_items,
            column: :id,
            name: "playback_items_parent_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          )

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_played_at, :utc_datetime_usec
      add :played, :boolean, null: false
      add :position_bytes, :bigint
      add :position_ms, :bigint, null: false
      add :keeps_place, :boolean, null: false
      add :favourite, :boolean, null: false
      add :live, :boolean, null: false
      add :format, :text
      add :container_format, :text
      add :transport, :text
      add :url, :text
      add :published_at, :utc_datetime_usec
      add :rank, :bigint, null: false
      add :duration_ms, :bigint
      add :artwork_url, :text
      add :description, :text
      add :subtitle, :text
      add :title, :text, null: false
      add :kind, :text, null: false
      add :source_ref, :text, null: false
      add :source, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:playback_items, [:source, :source_ref],
             name: "playback_items_source_ref_index"
           )

    create table(:playback_item_facets, primary_key: false) do
      add :facet_id,
          references(:playback_facets,
            column: :id,
            name: "playback_item_facets_facet_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false

      add :item_id,
          references(:playback_items,
            column: :id,
            name: "playback_item_facets_item_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:playback_facets, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :value, :map, null: false
      add :key, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:playback_item_facets, [:item_id, :facet_id],
             name: "playback_item_facets_item_facet_index"
           )

    create unique_index(:playback_facets, [:key, :value], name: "playback_facets_key_value_index")
  end

  def down do
    drop_if_exists unique_index(:playback_facets, [:key, :value],
                     name: "playback_facets_key_value_index"
                   )

    drop_if_exists unique_index(:playback_item_facets, [:item_id, :facet_id],
                     name: "playback_item_facets_item_facet_index"
                   )

    drop table(:playback_facets)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `playback_item_facets` table without the `playback_item_facets_item_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `playback_item_facets` table without the `playback_item_facets_facet_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:playback_item_facets)

    drop_if_exists unique_index(:playback_items, [:source, :source_ref],
                     name: "playback_items_source_ref_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `playback_items` table without the `playback_items_parent_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:playback_items)
  end
end