defmodule MyHiFi.Repo.Migrations.AddCacheEntries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cache_entries, primary_key: false) do
      add :variant_digest, :text
      add :variant_name, :text

      add :variant_of_blob_id,
          references(:cache_entries,
            column: :id,
            name: "cache_entries_variant_of_blob_id_fkey",
            type: :uuid
          )

      add :pending_variants, :boolean, null: false
      add :pending_analyzers, :boolean, null: false
      add :pending_purge, :boolean, null: false
      add :analyzers, :map, default: %{}
      add :metadata, :map, default: %{}
      add :service_opts, :map, default: %{}
      add :service_name, :text, null: false
      add :checksum, :text
      add :byte_size, :bigint
      add :content_type, :text
      add :filename, :text, null: false
      add :key, :text, null: false
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :keep, :boolean, null: false
      add :last_accessed_at, :utc_datetime_usec, null: false
      add :entry_key, :text, null: false
      add :namespace, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:cache_entries, [:namespace, :entry_key],
             name: "cache_entries_namespace_entry_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(:cache_entries, [:namespace, :entry_key],
                     name: "cache_entries_namespace_entry_key_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `cache_entries` table without the `cache_entries_variant_of_blob_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:cache_entries)
  end
end