defmodule MyHiFi.Repo.Migrations.AddCacheAttachments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cache_attachments, primary_key: false) do
      add :entry_id,
          references(:cache_entries,
            column: :id,
            name: "cache_attachments_entry_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :record_id, :uuid, null: false
      add :record_type, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:cache_attachments, [:entry_id, :record_type, :record_id],
             name: "cache_attachments_entry_record_index"
           )
  end

  def down do
    drop_if_exists unique_index(:cache_attachments, [:entry_id, :record_type, :record_id],
                     name: "cache_attachments_entry_record_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `cache_attachments` table without the `cache_attachments_entry_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:cache_attachments)
  end
end