defmodule PiFi.Repo.Migrations.AddItemNumberAndDisc do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:playback_items) do
      add :number, :bigint
      add :disc, :bigint
    end
  end

  def down do
    alter table(:playback_items) do
      remove :disc
      remove :number
    end
  end
end