defmodule PiFi.Repo.Migrations.AddEpisodePositionBytes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:podcast_episodes) do
      add :position_bytes, :bigint
    end
  end

  def down do
    alter table(:podcast_episodes) do
      remove :position_bytes
    end
  end
end