defmodule MyHiFi.Repo.Migrations.AddItemReleaseYear do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:playback_items) do
      add :release_year, :bigint
    end
  end

  def down do
    alter table(:playback_items) do
      remove :release_year
    end
  end
end