defmodule MyHiFi.Repo.Migrations.CaseInsensitiveTitleOrder do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:playback_items, ["source", "kind", "title"],
                     name: "playback_items_source_kind_title_index"
                   )

    execute("""
    CREATE INDEX playback_items_source_kind_title_nocase_index
    ON playback_items (source, kind, title COLLATE NOCASE)
    """)
  end

  def down do
    execute("""
    DROP INDEX playback_items_source_kind_title_nocase_index
    """)

    create index(:playback_items, ["source", "kind", "title"])
  end
end