defmodule PiFi.Repo.Migrations.IndexUuidReads do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:cache_entries, ["variant_of_blob_id"])

    execute("""
    CREATE INDEX playback_items_id_text_index
    ON playback_items (CAST(id AS TEXT))
    """)

    execute("""
    CREATE INDEX playback_items_parent_id_text_index
    ON playback_items (CAST(parent_id AS TEXT))
    """)
  end

  def down do
    execute("""
    DROP INDEX playback_items_parent_id_text_index
    """)

    execute("""
    DROP INDEX playback_items_id_text_index
    """)

    drop_if_exists index(:cache_entries, ["variant_of_blob_id"],
                     name: "cache_entries_variant_of_blob_id_index"
                   )
  end
end