defmodule PiFi.Repo.Migrations.AddFavouritedAtAndByteSize do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:playback_items) do
      add :byte_size, :bigint
      add :favourited_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:playback_items) do
      remove :favourited_at
      remove :byte_size
    end
  end
end