defmodule PiFi.Repo.Migrations.IndexCacheSize do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:cache_entries, ["byte_size"])
  end

  def down do
    drop_if_exists index(:cache_entries, ["byte_size"], name: "cache_entries_byte_size_index")
  end
end