defmodule MyHiFi.Repo.Migrations.ShowNamesItsItem do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # alter table(:podcast_shows) do
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :subscribed
    # end
    # 

    alter table(:podcast_shows) do
      add :item_id,
          references(:playback_items,
            column: :id,
            name: "podcast_shows_item_id_fkey",
            type: :uuid
          )
    end
  end

  def down do
    alter table(:podcast_shows) do
      remove :item_id
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `podcast_shows` table without the `podcast_shows_item_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    # alter table(:podcast_shows) do
    # This is the `down` migration of the statement:
    #
    #     remove :subscribed
    #
    # 
    # add :subscribed, :boolean, null: false
    # end
    # 
  end
end